# Generated by Django 5.1.3 on 2025-03-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='farm_type',
        ),
    ]
