# Generated by Django 5.1.3 on 2025-03-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crops/'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='location',
            field=models.CharField(choices=[('Harare', 'Harare'), ('Bulawayo', 'Bulawayo'), ('Mutare', 'Mutare'), ('Gweru', 'Gweru'), ('Kwekwe', 'Kwekwe'), ('Chinhoyi', 'Chinhoyi'), ('Masvingo', 'Masvingo'), ('Kadoma', 'Kadoma'), ('Marondera', 'Marondera'), ('Zvishavane', 'Zvishavane'), ('Victoria Falls', 'Victoria Falls'), ('Kariba', 'Kariba'), ('Bindura', 'Bindura'), ('Chipinge', 'Chipinge')], default='Harare', max_length=255),
        ),
    ]
